### PR TITLE
MNT: Re-rendered with conda-smithy 3.1.12 and pinning 2018.11.27

### PR DESCRIPTION
**Pull request by hobu**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hobu** [comment]
I would like to merge a rerendered FLANN so we can rerender PCL, which is currently dependent on an outdated HDF.

**Comment by hobu** [comment]
Well, shoot. Pinning 12.04 moved HDF back to 1.10.2 on windows, which is exactly what we don't want.

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
> Well, shoot. Pinning 12.04 moved HDF back to 1.10.2 on windows, which is exactly what we don't want.

Why? If you need builds with older pins we must do them in a branch to avoid breaking the main recipe.

**Comment by hobu** [comment]
> Why? If you need builds with older pins we must do them in a branch to avoid breaking the main recipe.

Looks like this current rerender has 1.10.4 on windows, which is what we need.

**Comment by hobu** [comment]
> Looks like this current rerender has 1.10.4 on windows, which is what we need.

~Unfortunately it is still pulling HDF 1.10.2 
https://ci.appveyor.com/project/conda-forge/pdal-feedstock/builds/21165597#L332~

Looked at the wrong build. Windows seems [to be building](https://ci.appveyor.com/project/conda-forge/pdal-feedstock/builds/21183027).

**Pull request merged**
