### PR TITLE
Update to flann 1.9.2

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Running into issues in https://github.com/conda-forge/colmap-feedstock/pull/24 because it uses C++17 which is not supported by flann 1.9.1

**Comment by Tobias-Fischer** [comment]
Fix #28

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Hi @conda-forge/flann @traversaro - I've gone down a rabbit hole and some downstream projects suddenly fail to compile because flann 1.9.1 doesn't support C++17 compilers; whereas 1.9.2 should. Unfortunately pkg-config can't find `lz4` on Windows; I tried to pass directly the `LZ4_LIBRARIES` in https://github.com/conda-forge/flann-feedstock/pull/41/commits/c269611fb4e66d3806b4b933e16b2156bce6c9ed but that didn't to the job. Do you have other ideas? Do we need to go via cmake?

**Comment by Tobias-Fischer** [comment]
Hi @conda-forge/flann - this is ready for review.

Reminder for myself: We need to open a PR in the conda-forge-pinning-feedstock to bump the version once this is merged.

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
Thanks @Tobias-Fischer ! I will wait for comments for other maintainers (if any) and then I will merge.

**Comment by traversaro** [comment]
> Reminder for myself: We need to open a PR in the conda-forge-pinning-feedstock to bump the version once this is merged

In theory that is handled by the boys, together with opening a migration.

**Comment by Tobias-Fischer** [comment]
Thanks @traversaro - talking about bots, do you know why they didn't open a PR with the version bump here?

**Comment by traversaro** [comment]
Sorry for the late request, but can you also add the run_exports here? In this way we can remove this line: https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/4421234e5eeadd98f9c91a696c5d1699f3094633/recipe/conda_build_config.yaml#L182 when we bump the library in conda-forge-pinning. I would do it myself but I am just with my mobile phone for a  few days.

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
@traversaro - good catch! All done.

**Comment by traversaro** [comment]
Thanks!

**Comment by traversaro** [comment]
> Thanks @traversaro - talking about bots, do you know why they didn't open a PR with the version bump here?

No idea, in general errors in version update bots can be found in:
* https://conda-forge.org/status/#version_updates
* https://github.com/regro/cf-scripts/actions/workflows/bot-versions.yml

I do not see anything strange related to flann now, the output of the bot is:
~~~
2023-10-22T15:28:23.9382174Z 2023-10-22 15:28:23,937 INFO     conda_forge_tick.update_upstream_versions || itr  1286 - eta   227s: flann - 1.9.2 - 1.9.2
~~~

but once we have again the same problem, those two are the points that we should monitor.

**Pull request merged**
