### PR TITLE
Enable flann_cpp imported library creation for Windows build

### PR DESCRIPTION
**Pull request by seanyen**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

* Enable `flann_cpp` imported library creation for downstream project to link against on Windows.

### CODE REVIEW

**Comment by seanyen** [comment]
@conda-forge-admin, please rerender

**Comment by seanyen** [comment]
@conda-forge-admin, please rerender

**Comment by seanyen** [comment]
@conda-forge-admin, please rerender

**Comment by seanyen** [comment]
@conda-forge/flann This is ready for review and merge. Thanks!

**Comment by seanyen** [comment]
@conda-forge/flann @conda-forge/staged-recipes Friendly ping. This is ready for review and merge. Thanks!

**Comment by xhochy** [comment]
Thanks @seanyen for taking care of this.

**Pull request merged**
